### ISSUE TITLE
Creation is sometimes forcing a absolute link to be inserted

### ISSUE THREAD

**Issue by fakeharxy** [SimonTC/obsidian-note-autocreation#10]
I'm sorry I can't be more specific with this bug, but sometimes, when I am using the @./ functionality, something is happening that causes Obsidian to think that there is a duplicate file and use the whole absolute link in the file. I can't figure out when it happens, I'm sorry, but I thought for a while it might be something to do with capital letters at the beginning of the file name (or lack thereof) but I can't accurately reproduce it. 

What I will say is I have at least one file created using the @./ function, with a lowercase letter as the first letter, let's say it's called 'hello.md', and Obsidian for some reason also thinks there is a file called Hello.md, and it won't let me change the name of hello.md to have a capital letter, as it says it is a duplicate. This duplicate file does not appear in the file tree.

Sorry I can't be more help. If you have any questions, or anything you'd like me to try, I'll do what I can.

**Comment by SimonTC** [comment]
Thanks for the report!

What operating system are you using? If you are using Windows then this explains it. Windows does not distinguish between capital letters and lower case letters on file and folder names. If you already have a file named hello.md you won't be able to add a new file in the same folder called Hello.md. You might have to rename the file from outside of Obsidian in this case.

**Comment by fakeharxy** [comment]
I'm actually on a mac! Could it still be the same thing?

**Comment by SimonTC** [comment]
Yes, I think it is. 
You can test it easily outside Obsidian by creating a file with only lowercase letters in the name and then try to create another file with the same name, but with capital letters and see if it is possible.
