### ISSUE TITLE
 New root notes are not being created in the default location specified in "Default location for new notes"

### ISSUE THREAD

**Issue by nimide** [SimonTC/obsidian-note-autocreation#11]
I'm not sure if it's just me, but I can't seem to get the plugin to create notes in any folder put into the "Default location for new notes". It always defaults to the root folder.

**Comment by nimide** [comment]
To answer some questions I saw you ask other issue creators:
Obsidian version: v1.1.9
Plugin version: v1.3.1
What device are you running Obsidian on: Linux machine

**Comment by nimide** [comment]
Also, the folder I would like to put new root notes into is "+ Encounters" in the root of my vault. Thought that might help with testing.

**Comment by SimonTC** [comment]
Thanks for the report!

I tested it myself and I can also reproduce it. I will investigate and hopefully have a fix for this soon

**Comment by SimonTC** [comment]
It is not related to the name of the folder. I could reproduce it with a folder called folder2

**Comment by nimide** [comment]
Thanks for looking into it! I really appreciate all the hard work you put into creating this Obsidian plugin.

**Comment by SimonTC** [comment]
This issue has now been fixed in release 1.3.2

**Comment by nimide** [comment]
Thank you!
