### ISSUE TITLE
New root notes being created in the default location specified in "Default location for new notes" are defaulting to lowercase folders.

### ISSUE THREAD

**Issue by nimide** [SimonTC/obsidian-note-autocreation#13]
This is related to #11. The initial issue with the "Default location for new notes" field was for the most part fixed. However, regardless of the case in that field, this plugin is defaulting to all lowercase. For example: "+ Encounters" is where I would like the new root notes to be placed. However, the plugin appears to be defaulting to the "+ encounters" folder, which doesn't exist. Since the folder doesn't exist, it puts the new root note into the root folder. If I rename the folder and the "Default location for new notes" field to "+ encounters", the plugin works as expected.

**Comment by SimonTC** [comment]
Thanks for this bug report and sorry that this bug has fallen through the cracks. 
I apparently had no tests with capitalized folder names. I am correcting that oversight now and making a fix.

**Comment by SimonTC** [comment]
This issue has now been fixed in release 1.3.3

**Comment by nimide** [comment]
No worries at all. Thank you for all the hard work!
