### ISSUE TITLE
Not working within tasks

### ISSUE THREAD

**Issue by tobiasarndt** [SimonTC/obsidian-note-autocreation#14]
I am quite new to obsidian, so this might just be user error.

When is was to create a link in a task the link selection is not triggered.

eg.: - [ ] new task with more info here: @
I'm only able to trigger the link selection, if I first "break" the task  by deleting one of the brackets.

**Comment by SimonTC** [comment]
That is very odd. I just tested it myself and it works correctly for me. Do you have other plugins enabled?

**Comment by tobiasarndt** [comment]
I have:
- Calendar; Version 1.5.10
- Dataview; Version 0.5.56
- Note Auto Creator; Version 1.4.0
- Tasks; Version 4.2.0

I tried disabling the Auto-suggest of tasks, but that did not change anything for me. Except for that everything is on default settings.

To rule out user error:
typing: - @ works, but - [ ] @ does not

**Comment by SimonTC** [comment]
I now tried to create a completely new vault with the same plugins installed as you have. 
I still could not replicate the issue.

Could you try to see create a new vault and do the same?

What operating system are you running on? It should not influence anything, but you never know...

**Comment by tobiasarndt** [comment]
ok, I created a new vault and the issue is gone... Thanks for the help! When I figure out what in my configuration caused the issue i will update this.
