### ISSUE TITLE
Template name does not appear on mobile

### ISSUE THREAD

**Issue by brimwats** [SimonTC/obsidian-note-autocreation#3]
I have a template called "person template" and another called "person automove template" but it is not possible to distinguish between the two. ideally I'd be able to know which one I was applying

a visual
![image](https://user-images.githubusercontent.com/73113656/171558170-1b6b1adf-c718-4628-a04c-a7c76c656268.png)

**Comment by brimwats** [comment]
(except I have no idea what /kb/construct-validity means, it doesn't appear in a search, only using this plugin)

**Comment by brimwats** [comment]
it also doesn't work on minimal 

![Uploading Screenshot_20220602-143321_Obsidian.jpg…]()

**Comment by SimonTC** [comment]
Thanks for the testing! This is very odd. When I tested with the themes you mention everything worked as expected.

Some questions:
1. Is the issue the same when using the standard Obsidian theme? I would like to be certain this isn't theme related
3. What have you defined as the template folder in Templater?
4. If you search for one of the templates using only the @ symbol what is shown then? I have a theory that maybe the plugin fails to grab the names of the templates for some reason so I would like to see what happens when you search for the template as if it was a normal note

**Comment by SimonTC** [comment]
> (except I have no idea what /kb/construct-validity means, it doesn't appear in a search, only using this plugin)
> 
> ah I found it, it's a link: ![image](https://user-images.githubusercontent.com/73113656/171741275-bab755ce-dff8-46ef-b85e-b5e6fda6a284.png)

This is a bug. The plugin should not include weblinks. Thanks for catching that

**Comment by brimwats** [comment]
1. it does seem to happen on default



I went and disabled all CSS suggestions too and it still happens 

2. templater folder is 000 - Landing Page. Inbox. KO. Meta/_Templates

3. they appear 
![Screenshot_20220603-005131_Obsidian](https://user-images.githubusercontent.com/73113656/171813703-3a660ce6-1b4e-452d-8180-e592b82b05c3.jpg)

4.

**Comment by brimwats** [comment]
all debugging info:

SYSTEM INFO:
	Operating system: android 12 (samsung SM-G991U)
	Login status: not logged in
	Live preview: on
	Legacy editor: on
	Base theme: light
	Community theme: Primary
	Snippets enabled: 17
	Safe mode: off
	Plugins installed: 49
	Plugins enabled: 28
		1: Templater
		2: Hider
		3: Advanced URI
		4: MetaEdit
		5: QuickAdd
		6: Collapse All
		7: Supercharged Links
		8: Another Quick Switcher
		9: Folder Note Core
		10: Periodic Notes
		11: Bartender
		12: Style Settings
		13: AidenLx's Folder Note
		14: Smarter Markdown Hotkeys
		15: Better Command Palette
		16: Footnote Shortcut
		17: Dynamic Table of Contents
		18: Settings Search
		19: Limelight
		20: Customizable Page Header and Title Bar
		21: Advanced Mobile Toolbar
		22: Obsidian42 - BRAT
		23: Code Editor Shortcuts
		24: Various Complements
		25: Omnisearch
		26: Banners
		27: Map View
		28: Note Auto Creator

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by brimwats** [comment]
It also happens on desktop: 

![image](https://user-images.githubusercontent.com/73113656/171814248-e7a6d361-f7ef-434e-942a-17433f3fea56.png)

I have a lot more installed on desktop

SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.14.2
	Operating system: Windows 10 Education 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 20
	Safe mode: off
	Plugins installed: 101
	Plugins enabled: 81
		1: Style Settings
		2: Folder Note Core
		3: Templater
		4: Collapse All
		5: Customizable Page Header and Title Bar
		6: Reset Font Size
		7: Advanced URI
		8: Another Quick Switcher
		9: Bartender
		10: Better Command Palette
		11: Breadcrumbs
		12: Code Editor Shortcuts
		13: Contextual Typography
		14: Core Search Assistant
		15: Customizable Sidebar
		16: Dataview
		17: Hider
		18: Grandfather
		19: Format Hotkeys
		20: Homepage
		21: Hotkey Helper
		22: Zoom
		23: Word Sprint
		24: Webhook Plugin
		25: Various Complements
		26: Recent Files
		27: QuickAdd
		28: Quick Explorer
		29: Plugin Changelogs
		30: Pane Relief
		31: Outliner
		32: Obsidian Tabs
		33: Sentence Navigator
		34: File Info Panel
		35: Smarter Markdown Hotkeys
		36: Cycle through Panes
		37: Toggle Readable Line Length
		38: File Explorer Note Count
		39: Key Promoter
		40: LanguageTool Integration
		41: MySnippets
		42: Multi-Column Markdown
		43: MetaEdit
		44: Local images
		45: Linked Data Vocabularies
		46: Natural Language Dates
		47: Tag Wrangler
		48: File path to URI
		49: Link Archive
		50: Tweet to Markdown
		51: Settings Search
		52: Footnote Shortcut
		53: Obsidian Charts
		54: Dynamic Table of Contents
		55: Periodic Notes
		56: Hover Editor
		57: AidenLx's Folder Note
		58: Zotero Integration
		59: Waypoint
		60: Banners
		61: Custom Frames
		62: AidenLx's Folder Note - folderv component
		63: Macros
		64: Open with
		65: Obsidian42 - BRAT
		66: List Modified
		67: Paste image rename
		68: Snippet Downloader
		69: Longform
		70: Minimal Theme Settings
		71: Omnisearch
		72: Advanced Tables
		73: Excalidraw
		74: Excel to Markdown Table
		75: Text Generator
		76: Limelight
		77: Obsidian Enhancing Export
		78: Map View
		79: DB Folder
		80: Supercharged Links
		81: Note Auto Creator

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by brimwats** [comment]
It does not happen on desktop sandbox vault w just autocreator and templater

![image](https://user-images.githubusercontent.com/73113656/171814930-3c62f214-ffb2-4133-9c3c-3bd1c384610e.png)

**Comment by SimonTC** [comment]
Thanks a lot! I can reproduce this now. It has something to do with the template folder path. I will try to fix it this weekend

**Comment by brimwats** [comment]
yay!

**Comment by SimonTC** [comment]
Apparently, my weekend started already. I just made a [new public release](https://github.com/SimonTC/obsidian-note-autocreation/releases/tag/1.1.1) with a fix for the folder issue.
I hadn't considered that folders and files could have dots in the path before the file extension. 
I tested it with your folder name and it works now.

Thanks for the help in finding this issue!

**Comment by brimwats** [comment]
happy weekend! thank you SO much—I can finally delete the 74 templates I've had around forever. This plugin will save me an incredible about of time—it's perfect when paired with supercharged links and breadcrumbs!
