### ISSUE TITLE
FR: Please support quickadd

### ISSUE THREAD

**Issue by YIRU69** [SimonTC/obsidian-note-autocreation#4]
Hi, friend. I love you plugin very much. It help me a lot.
When I create a note, I usually use quickadd template. 
So can it support quickadd.
Appreciation!

**Comment by SimonTC** [comment]
Hi! I'm very happy you like the plugin. 

I will see what I can do to also support Quickadd templates. I need to do some digging though as I'm not sure there is a public API I easily can use.

**Comment by brimwats** [comment]
@SimonTC here is the API https://github.com/chhoumann/quickadd/blob/bce0b4cdac44b867854d6233796e3406dfd163c6/docs/QuickAddAPI.md

**Comment by SimonTC** [comment]
@brimwats thanks for the link. Unfortunately to use that API I need access to the params object which you only have access to through QuickAdd macros.  (See the comment [here](https://github.com/chhoumann/quickadd/discussions/135#discussioncomment-1623967)).
It is simple enough to get access to the configured QuickAdd choices so I am now thinking that maybe I can get QuickAdd to execute the choice somehow. I have to look into how QuickAdd works and maybe contact the author to see if something can be done.

**Comment by YIRU69** [comment]
@SimonTC Quickadd plugin had update and add the API. Could it help you to achieve the enhancement?

**Comment by SimonTC** [comment]
Could you actually give me an example of a template you are using @YIRU69? And maybe explain how you would expect it to work with Note Auto Creator? I'm not using QuickAdd myself, so I am not so familiar with typical use cases.

**Comment by YIRU69** [comment]
It is very similar to the Templater plugin, except that it requires the specification of certain parameters for input, such as the {{VALUE}} parameter. For example, if there is title: {{VALUE}} in my notes, a prompt window will appear when I create a note, allowing me to input the parameter. It supports multiple parameters, and you can try it out when you have time.

My personal usage scenario is not complicated, mainly using one parameter. I hope that when using the template quickly, I can directly input the {{VALUE}} parameter. Please let me know if there are any questions, and I will respond as soon as possible.

**Comment by SimonTC** [comment]
@YIRU69 there is now a [beta release](https://github.com/SimonTC/obsidian-note-autocreation/releases/tag/1.3.991) for this. Life has gotten in the way, so I have not had time to test this thoroughly, but from my initial testing it works correctly. 
Could you try it out and see if there are any issues?
You can either install the update manually or use [BRAT](https://github.com/TfTHacker/obsidian42-brat) to install it.
I have updated the readme with instructions on how to use templates from QuickAdd, but it basically works the same as templates from Templater.

**Comment by YIRU69** [comment]
It words that I make a quick test.
