### ISSUE TITLE
Feature Request: insert folder and then let me add new note

### ISSUE THREAD

**Issue by roleforgaming** [SimonTC/obsidian-note-autocreation#7]
It would be a nice QOL feature to have the ability to quick select the nested folder I'm looking for then add "/new note" from there. 

Right now I can type: `@Skills` and it will show me the Skills folder, but when I click it, it simply links to it. So when I want to add a new note to Skills, I have to type the entire folder path: `3. Systems/Cortex Prime/Prime Core/8. Skills/newnote` to create a new note. It would be nice if I could type `@Skills`, click it, and it shows me the path that I can add `/newnote` to, then execute it with `enter`.

**Comment by SimonTC** [comment]
Thanks for your request. That is an excellent idea. I will see if I can't find a way to support it.

**Comment by SimonTC** [comment]
This feature is now in beta testing. You can try it out if you are using [BRAT](https://github.com/TfTHacker/obsidian42-brat) or [by downloading it manually](https://github.com/SimonTC/obsidian-note-autocreation/releases/tag/1.2.992). 
I do expect to release it within a week to two, so you can also wait until then.
Until it is released you can read documentation about the feature here: https://github.com/SimonTC/obsidian-note-autocreation/tree/develop#include-folders-in-suggestions
There are actually some gifs included in the readme, but they will only be shown when I have released the next version officially.
Until then you can see the functionality here:

**Folder paths always shown**
![Always show folder paths](https://raw.githubusercontent.com/SimonTC/obsidian-note-autocreation/develop/readme_assets/NAC_Include_folders_always.gif)

**Folder paths only shown on trigger**
![Only show folder paths on trigger](https://raw.githubusercontent.com/SimonTC/obsidian-note-autocreation/develop/readme_assets/NAC_Folders_with_trigger.gif)

**Comment by SimonTC** [comment]
This feature currently does not work on mobile devices and tablets. I will try to fix that during the weekend.

**Comment by SimonTC** [comment]
Hi @roleforgaming .

This feature is now included in release 1.3.0

**Comment by SimonTC** [comment]
(And it works on both mobile and PC)
